Repository k-cloud-labs/kluster-capacity, pull requests merged in 2023-03, with the labels that each got.

#67 feat: add useful log for ss,ce cmd and do some refactoring
  app/cmds/capacityestimation/capacityestimation.go
  app/cmds/clustercompression/clustercompression.go
  app/cmds/schedulersimulation/schedulersimulation.go
  app/root.go
  pkg/framework/doc.go
  pkg/framework/kubescheduler.go
  pkg/framework/volcano.go
  pkg/interface.go
  pkg/simulator/capacityestimation/podgenerator.go
  pkg/simulator/capacityestimation/report.go
  pkg/simulator/capacityestimation/simulator.go
  pkg/simulator/clustercompression/nodeFilter.go
  pkg/simulator/clustercompression/options.go
  pkg/simulator/clustercompression/report.go
  pkg/simulator/clustercompression/simulator.go
  pkg/simulator/schedulersimulation/report.go
  pkg/simulator/schedulersimulation/simulator.go
Labels: enhancement, size/L

#68 feat: do some refact
  app/cmds/capacityestimation/capacityestimation.go
  app/cmds/clustercompression/clustercompression.go
  app/cmds/schedulersimulation/schedulersimulation.go
  app/root.go
  pkg/framework/doc.go
  pkg/framework/kubescheduler.go
  pkg/framework/volcano.go
  pkg/interface.go
  pkg/simulator/capacityestimation/podgenerator.go
  pkg/simulator/capacityestimation/report.go
  pkg/simulator/capacityestimation/simulator.go
  pkg/simulator/clustercompression/nodeFilter.go
  pkg/simulator/clustercompression/options.go
  pkg/simulator/clustercompression/report.go
  pkg/simulator/clustercompression/simulator.go
  pkg/simulator/schedulersimulation/report.go
  pkg/simulator/schedulersimulation/simulator.go
Labels: size/L

#70 feat: simplify usage
  README-ZH.md
  README.md
  app/cmds/capacityestimation/capacityestimation.go
  app/cmds/clustercompression/clustercompression.go
  app/cmds/option.go
  app/cmds/schedulersimulation/schedulersimulation.go
  pkg/utils/utils.go
Labels: enhancement, size/M

#71 feat: add pod and node schedule times to cc and print it when verbose
  pkg/framework/kubescheduler.go
  pkg/interface.go
  pkg/simulator/capacityestimation/report.go
  pkg/simulator/clustercompression/report.go
  pkg/simulator/clustercompression/simulator.go
  pkg/simulator/schedulersimulation/report.go
  pkg/status.go
Labels: enhancement

#72 feat: use go releaser to auto update homebrew and krew
  .github/workflows/release.yml
  .goreleaser.yml
  .krew.yaml
  README-ZH.md
  README.md
Labels: enhancement, size/L

#73 feat: add pod and node schedule times to cc and print it when verbose
  pkg/framework/kubescheduler.go
  pkg/interface.go
  pkg/plugins/generic/plugin.go
  pkg/simulator/capacityestimation/report.go
  pkg/simulator/capacityestimation/simulator.go
  pkg/simulator/clustercompression/report.go
  pkg/simulator/clustercompression/simulator.go
  pkg/simulator/schedulersimulation/report.go
  pkg/status.go
Labels: enhancement

#75 fix a bug when use cc with exclude taint node false
  pkg/simulator/clustercompression/nodeFilter.go
  pkg/simulator/clustercompression/options.go
  pkg/simulator/clustercompression/simulator.go
Labels: bug

#77 feat: import auth plugin to support work on GKE clusters etc
  app/root.go
Labels: enhancement, size/S

#79 feat: auto krew
  .krew.yaml
Labels: enhancement, size/S

#81 fix: wait cache synced
  pkg/framework/kubescheduler.go
Labels: bug

#82 Feature nodecache
  .github/workflows/label.yml
  app/cmds/clustercompression/options/clustercompression.go
  pkg/framework/kubescheduler.go
  pkg/interface.go
  pkg/simulator/capacityestimation/simulator.go
  pkg/simulator/clustercompression/nodeFilter.go
  pkg/simulator/clustercompression/options.go
  pkg/simulator/clustercompression/simulator.go
  pkg/simulator/schedulersimulation/report.go
  pkg/simulator/schedulersimulation/simulator.go
Labels: enhancement
