Repository k-cloud-labs/kluster-capacity, pull requests merged in 2023-02, with the labels that each got.

#32 optimize the node filter to improve cc performance
  pkg/framework/clustercompression/nodeFilter.go
Labels: enhancement

#44 fix: fix a bug which result to incorrect status to save
  pkg/framework/capacityestimation/report.go
  pkg/framework/capacityestimation/simulator.go
  pkg/framework/generic.go
  pkg/framework/schedulersimulation/report.go
  pkg/framework/schedulersimulation/simulator.go
  pkg/interface.go
Labels: bug, size/S

#46 fix: fix a bug for ss caused by terminating pod
  pkg/framework/generic.go
  pkg/framework/schedulersimulation/simulator.go
Labels: bug

#48 fix: fix a bug for ss caused by terminating pod
  pkg/framework/generic.go
  pkg/framework/schedulersimulation/simulator.go
Labels: bug, size/S

#51 fix: restore cache errors when scheduling fails
  pkg/framework/clustercompression/simulator.go
Labels: bug

#52 fix: restore cache errors when scheduling fails
  pkg/framework/clustercompression/simulator.go
Labels: bug

#53 feat: ignore the effect of ds pod for ss
  pkg/framework/generic.go
  pkg/framework/schedulersimulation/report.go
  pkg/framework/schedulersimulation/simulator.go
Labels: enhancement

#54 feat: ignore the effect of ds pod for ss
  pkg/framework/generic.go
  pkg/framework/schedulersimulation/report.go
  pkg/framework/schedulersimulation/simulator.go
Labels: enhancement, size/M

#56 fix: a bug which may result to incorrect node when node have no pods
  pkg/framework/clustercompression/simulator.go
Labels: bug

#55 fix: a bug which may result to incorrect node when node have no pods
  pkg/framework/clustercompression/simulator.go
Labels: bug
